package com.example.abc.chinesemedicine.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import bean.ChinesePatentDrugSecondCategory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHINESE_PATENT_DRUG_SECOND_CATEGORY".
*/
public class ChinesePatentDrugSecondCategoryDao extends AbstractDao<ChinesePatentDrugSecondCategory, Long> {

    public static final String TABLENAME = "CHINESE_PATENT_DRUG_SECOND_CATEGORY";

    /**
     * Properties of entity ChinesePatentDrugSecondCategory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property FirstCategoryName = new Property(2, String.class, "firstCategoryName", false, "FIRST_CATEGORY_NAME");
    }


    public ChinesePatentDrugSecondCategoryDao(DaoConfig config) {
        super(config);
    }
    
    public ChinesePatentDrugSecondCategoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHINESE_PATENT_DRUG_SECOND_CATEGORY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"FIRST_CATEGORY_NAME\" TEXT);"); // 2: firstCategoryName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHINESE_PATENT_DRUG_SECOND_CATEGORY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ChinesePatentDrugSecondCategory entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String firstCategoryName = entity.getFirstCategoryName();
        if (firstCategoryName != null) {
            stmt.bindString(3, firstCategoryName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ChinesePatentDrugSecondCategory entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String firstCategoryName = entity.getFirstCategoryName();
        if (firstCategoryName != null) {
            stmt.bindString(3, firstCategoryName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ChinesePatentDrugSecondCategory readEntity(Cursor cursor, int offset) {
        ChinesePatentDrugSecondCategory entity = new ChinesePatentDrugSecondCategory( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // firstCategoryName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ChinesePatentDrugSecondCategory entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFirstCategoryName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ChinesePatentDrugSecondCategory entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ChinesePatentDrugSecondCategory entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ChinesePatentDrugSecondCategory entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
