package com.example.abc.chinesemedicine.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bean.ChineseMedicine;
import bean.HotSearch;
import bean.SearchHistory;
import bean.ChinesePatentDrug;
import bean.ChinesePatentDrugSecondCategory;
import bean.AcuPoint;
import bean.Prescription;

import com.example.abc.chinesemedicine.greendao.ChineseMedicineDao;
import com.example.abc.chinesemedicine.greendao.HotSearchDao;
import com.example.abc.chinesemedicine.greendao.SearchHistoryDao;
import com.example.abc.chinesemedicine.greendao.ChinesePatentDrugDao;
import com.example.abc.chinesemedicine.greendao.ChinesePatentDrugSecondCategoryDao;
import com.example.abc.chinesemedicine.greendao.AcuPointDao;
import com.example.abc.chinesemedicine.greendao.PrescriptionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chineseMedicineDaoConfig;
    private final DaoConfig hotSearchDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig chinesePatentDrugDaoConfig;
    private final DaoConfig chinesePatentDrugSecondCategoryDaoConfig;
    private final DaoConfig acuPointDaoConfig;
    private final DaoConfig prescriptionDaoConfig;

    private final ChineseMedicineDao chineseMedicineDao;
    private final HotSearchDao hotSearchDao;
    private final SearchHistoryDao searchHistoryDao;
    private final ChinesePatentDrugDao chinesePatentDrugDao;
    private final ChinesePatentDrugSecondCategoryDao chinesePatentDrugSecondCategoryDao;
    private final AcuPointDao acuPointDao;
    private final PrescriptionDao prescriptionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chineseMedicineDaoConfig = daoConfigMap.get(ChineseMedicineDao.class).clone();
        chineseMedicineDaoConfig.initIdentityScope(type);

        hotSearchDaoConfig = daoConfigMap.get(HotSearchDao.class).clone();
        hotSearchDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        chinesePatentDrugDaoConfig = daoConfigMap.get(ChinesePatentDrugDao.class).clone();
        chinesePatentDrugDaoConfig.initIdentityScope(type);

        chinesePatentDrugSecondCategoryDaoConfig = daoConfigMap.get(ChinesePatentDrugSecondCategoryDao.class).clone();
        chinesePatentDrugSecondCategoryDaoConfig.initIdentityScope(type);

        acuPointDaoConfig = daoConfigMap.get(AcuPointDao.class).clone();
        acuPointDaoConfig.initIdentityScope(type);

        prescriptionDaoConfig = daoConfigMap.get(PrescriptionDao.class).clone();
        prescriptionDaoConfig.initIdentityScope(type);

        chineseMedicineDao = new ChineseMedicineDao(chineseMedicineDaoConfig, this);
        hotSearchDao = new HotSearchDao(hotSearchDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        chinesePatentDrugDao = new ChinesePatentDrugDao(chinesePatentDrugDaoConfig, this);
        chinesePatentDrugSecondCategoryDao = new ChinesePatentDrugSecondCategoryDao(chinesePatentDrugSecondCategoryDaoConfig, this);
        acuPointDao = new AcuPointDao(acuPointDaoConfig, this);
        prescriptionDao = new PrescriptionDao(prescriptionDaoConfig, this);

        registerDao(ChineseMedicine.class, chineseMedicineDao);
        registerDao(HotSearch.class, hotSearchDao);
        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(ChinesePatentDrug.class, chinesePatentDrugDao);
        registerDao(ChinesePatentDrugSecondCategory.class, chinesePatentDrugSecondCategoryDao);
        registerDao(AcuPoint.class, acuPointDao);
        registerDao(Prescription.class, prescriptionDao);
    }
    
    public void clear() {
        chineseMedicineDaoConfig.clearIdentityScope();
        hotSearchDaoConfig.clearIdentityScope();
        searchHistoryDaoConfig.clearIdentityScope();
        chinesePatentDrugDaoConfig.clearIdentityScope();
        chinesePatentDrugSecondCategoryDaoConfig.clearIdentityScope();
        acuPointDaoConfig.clearIdentityScope();
        prescriptionDaoConfig.clearIdentityScope();
    }

    public ChineseMedicineDao getChineseMedicineDao() {
        return chineseMedicineDao;
    }

    public HotSearchDao getHotSearchDao() {
        return hotSearchDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public ChinesePatentDrugDao getChinesePatentDrugDao() {
        return chinesePatentDrugDao;
    }

    public ChinesePatentDrugSecondCategoryDao getChinesePatentDrugSecondCategoryDao() {
        return chinesePatentDrugSecondCategoryDao;
    }

    public AcuPointDao getAcuPointDao() {
        return acuPointDao;
    }

    public PrescriptionDao getPrescriptionDao() {
        return prescriptionDao;
    }

}
