package com.example.abc.chinesemedicine.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import bean.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property UserIconPath = new Property(2, String.class, "userIconPath", false, "USER_ICON_PATH");
        public final static Property Motto = new Property(3, String.class, "motto", false, "MOTTO");
        public final static Property LastestLearningSubject = new Property(4, String.class, "lastestLearningSubject", false, "LASTEST_LEARNING_SUBJECT");
        public final static Property LastestLearningItem = new Property(5, String.class, "lastestLearningItem", false, "LASTEST_LEARNING_ITEM");
    }

    private DaoSession daoSession;


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"USER_ICON_PATH\" TEXT," + // 2: userIconPath
                "\"MOTTO\" TEXT," + // 3: motto
                "\"LASTEST_LEARNING_SUBJECT\" TEXT," + // 4: lastestLearningSubject
                "\"LASTEST_LEARNING_ITEM\" TEXT);"); // 5: lastestLearningItem
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String userIconPath = entity.getUserIconPath();
        if (userIconPath != null) {
            stmt.bindString(3, userIconPath);
        }
 
        String motto = entity.getMotto();
        if (motto != null) {
            stmt.bindString(4, motto);
        }
 
        String lastestLearningSubject = entity.getLastestLearningSubject();
        if (lastestLearningSubject != null) {
            stmt.bindString(5, lastestLearningSubject);
        }
 
        String lastestLearningItem = entity.getLastestLearningItem();
        if (lastestLearningItem != null) {
            stmt.bindString(6, lastestLearningItem);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String userIconPath = entity.getUserIconPath();
        if (userIconPath != null) {
            stmt.bindString(3, userIconPath);
        }
 
        String motto = entity.getMotto();
        if (motto != null) {
            stmt.bindString(4, motto);
        }
 
        String lastestLearningSubject = entity.getLastestLearningSubject();
        if (lastestLearningSubject != null) {
            stmt.bindString(5, lastestLearningSubject);
        }
 
        String lastestLearningItem = entity.getLastestLearningItem();
        if (lastestLearningItem != null) {
            stmt.bindString(6, lastestLearningItem);
        }
    }

    @Override
    protected final void attachEntity(User entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // userIconPath
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // motto
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // lastestLearningSubject
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // lastestLearningItem
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserIconPath(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMotto(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLastestLearningSubject(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLastestLearningItem(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
